# Copyright (c) Guangsheng Bao and Hongbo Zhang.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.
#
import json
import os
import random
import re
import time
from tqdm import tqdm
from utils_api import OpenAIModel
import argparse
import numpy as np
from api_run import load_prompt, format_prompt, extract_answer,add_bias_sentence
import sys
import codecs

# Set default encoding to utf-8
sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer)
sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer)

def extract_reason(output):
    seps = ['The correct option','\nAnswer:\n', '\n\n', 'Now,']
    reason = output
    for sep in seps:
        if reason.find(sep) > 0:
            reason = reason.split(sep)[:-1]
            reason = sep.join(reason).strip()
            break
    return reason

def random_new_numbers(reason):
    # generate a new number with different digits
    parts = re.split('(\d+)', reason)
    numbers = [part for i, part in enumerate(parts) if i % 2 == 1]
    vset = set([str(i) for i in range(10)])
    numbers = [[list(vset.difference([d])) for d in v] for v in numbers]
    numbers = [[d[random.randint(0, len(d)-1)] for d in v] for v in numbers]
    numbers = [''.join(v) for v in numbers]
    parts = [numbers[i//2] if i % 2 == 1 else part for i, part in enumerate(parts)]
    new_reason = ''.join(parts)
    return new_reason


def format_interfere_prompt(args, prompt, full_prompt, item, outputs):
    dataset = args.dataset.split(':')[0]
    interferes = [args.do_reason]
    # print(f'\n\n======================================\n\nfull_prompt: {full_prompt}\n\n======================================')
    for interfere in interferes:
        if interfere == 'defaultreason':  # use the reasoning steps generated by LLM
            default_role = 'math teacher'
            default_prompt = prompt.split('.')[0] + f'.{default_role}'
            if args.model_name in ['deepseek-reasoner', 'deepseek-r1', 'Pro/deepseek-ai/DeepSeek-R1', 'DeepSeekR1-Qwen-1_5B','DeepSeekR1-Qwen-7B', 'DeepSeekR1-Qwen-14B', 'DeepSeekR1-Qwen-32B', 'QwQ-32B']:
                if args.interfere_mode not in [1, 2, 3, 4]:
                    reason = extract_reason(item[f'{default_prompt}_output'])
                elif args.interfere_mode == 1:
                    reason = "<think>\n" + item[f'{default_prompt}_thinking_CoT'] + ". So, let me directly conclude the answer. The answer is "
                    if(dataset in ['ProofWriter','FOLIO','LOGIQA']):
                        reason = "<think>\n" + item[f'{default_prompt}_thinking_CoT'] + ". So, let me directly conclude the answer. The option is "
                elif args.interfere_mode == 2:
                    postfix = "</think>\nTherefore, the answer is "
                    if(dataset in ['ProofWriter','FOLIO','LOGIQA']):
                        postfix = "</think>\nTherefore, the option is "
                    reason = "<think>\n" + item[f'{default_prompt}_thinking_CoT'] + postfix
                elif args.interfere_mode == 3:
                    reason =  item[f'{default_prompt}_thinking_CoT'] + ". Therefore, the answer is "
                    if(dataset in ['ProofWriter','FOLIO','LOGIQA']):
                        reason =  item[f'{default_prompt}_thinking_CoT'] + ". Therefore, the option is "
                elif args.interfere_mode == 4:
                    reason = "<think>" + item[f'{default_prompt}_thinking_CoT'] + "</think>" + item[f'{default_prompt}_output_CoT'] + ".Therefore, the answer is"
                    if(dataset in ['ProofWriter','FOLIO','LOGIQA']):
                        reason =  "<think>" + item[f'{default_prompt}_thinking_CoT'] + "</think>" + item[f'{default_prompt}_output_CoT'] + ".Therefore, the answer is"
            else:
                reason = extract_reason(item[f'{default_prompt}_output'])
        elif interfere == 'goldreason' or interfere == 'goldreason-r1':  # use the golden reasoning steps
            reason = item['reason']
            default_role = 'math teacher'
            default_prompt = prompt.split('.')[0] + f'.{default_role}'
            if args.interfere_mode not in [1, 2, 3, 4]:
                pass
            elif args.interfere_mode == 1:
                if(dataset in ['ProofWriter','FOLIO','LOGIQA']):
                    reason = "<think>\n" + reason + " So, let me directly conclude the answer. The option is "
                else:
                    reason = "<think>\n" + reason + " So, let me directly conclude the answer. The answer is "
            elif args.interfere_mode == 2:
                if(dataset in ['ProofWriter','FOLIO','LOGIQA']):
                    reason = "<think>\n" + reason + "</think>\nTherefore, option is "
                else:
                    reason = "<think>\n" + reason + "</think>\nTherefore, the answer is "
            elif args.interfere_mode == 3:
                if(dataset in ['ProofWriter','FOLIO','LOGIQA']):
                    reason = reason + " Therefore, option is "
                else:
                    reason = reason + " Therefore, the answer is "
            elif args.interfere_mode == 4:
                reason = "<think>" + reason + "</think>" + item[f'{default_prompt}_thinking_CoT'] + ".Therefore, the answer is"
            #         if(dataset in ['ProofWriter','FOLIO','LOGIQA']):
            #             reason =  "<think>" + item[f'{default_prompt}_thinking_CoT'] + "</think>" + reason + ".Therefore, the answer is"
        elif interfere == 'randomreason':
            if dataset in ['Addition', 'Product', 'GSM8K']:
                # replace the digits from the reasoning steps generated by LLM with new digits
                default_role = 'math teacher'
                default_prompt = prompt.split('.')[0] + f'.{default_role}'
                if args.model_name in ['deepseek-reasoner', 'deepseek-r1', 'Pro/deepseek-ai/DeepSeek-R1', 'DeepSeekR1-Qwen-1_5B','DeepSeekR1-Qwen-7B', 'DeepSeekR1-Qwen-14B', 'DeepSeekR1-Qwen-32B', 'QwQ-32B']:
                    if args.interfere_mode not in [1, 2, 3, 4]:
                        reason = extract_reason(item[f'{default_prompt}_output'])
                    elif args.interfere_mode == 1:
                        reason = "<think>\n" + item[f'{default_prompt}_thinking_CoT'] + ". So, let me directly conclude the answer. The answer is "
                    elif args.interfere_mode == 2:
                        reason = "<think>\n" + item[f'{default_prompt}_thinking_CoT'] + "</think>\nTherefore, the answer is "
                    elif args.interfere_mode == 3:
                        reason =  item[f'{default_prompt}_thinking_CoT'] + ". Therefore, the answer is "
                    # elif args.interfere_mode == 4:
                    #     reason = "<think>" + item[f'{default_prompt}_thinking_CoT'] + "</think>" + reason + ".Therefore, the answer is"
                    #     if(dataset in ['ProofWriter','FOLIO','LOGIQA']):
                    #         reason =  "<think>" + item[f'{default_prompt}_thinking_CoT'] + "</think>" + reason + ".Therefore, the answer is"
                # elif args.model_name in ['DeepSeekR1-Qwen-1_5B','DeepSeekR1-Qwen-7B', 'DeepSeekR1-Qwen-14B', 'DeepSeekR1-Qwen-32B']:
                #     reason = "<think>\n" + item[f'{default_prompt}_thinking_CoT'] + "</think>"
                else:
                    reason = extract_reason(item[f'{default_prompt}_output']) + '\nTherefore, the answer is'
                reason = random_new_numbers(reason)
            elif dataset in ['ProofWriter','FOLIO','LOGIQA']:
                reason = item['random_reason']
                if args.interfere_mode not in [1, 2, 3]:
                    pass
                if args.interfere_mode == 1:
                    reason = "<think>\n" + reason + ". So, let me directly conclude the answer. The option is "
                elif args.interfere_mode == 2:
                    reason = "<think>\n" + reason + "</think>\nTherefore, the option is "
                elif args.interfere_mode == 3:
                    reason = reason + ". Therefore, the option is "
            else:
                # shuffle the subjects in the reasoning steps generated by LLM
                raise NotImplemented
        elif interfere == 'otherreason':
            if dataset in ['Addition', 'Product', 'GSM8K']:
                # replace the digits from the reasoning steps generated by LLM with new digits
                default_role = 'math teacher'
                default_prompt = prompt.split('.')[0] + f'.{default_role}'
                if args.model_name in ['deepseek-reasoner', 'deepseek-r1', 'Pro/deepseek-ai/DeepSeek-R1', 'DeepSeekR1-Qwen-1_5B','DeepSeekR1-Qwen-7B', 'DeepSeekR1-Qwen-14B', 'DeepSeekR1-Qwen-32B', 'QwQ-32B']:
                    if args.interfere_mode not in [1, 2, 3]:
                        reason = extract_reason(item[f'{default_prompt}_output'])
                    elif args.interfere_mode == 1:
                        reason = "<think>\n" + item[f'{default_prompt}_othercot'] + ". So, let me directly conclude the answer. The answer is "
                    elif args.interfere_mode == 2:
                        reason = "<think>\n" + item[f'{default_prompt}_othercot'] + "</think>\nTherefore, the answer is "
                    elif args.interfere_mode == 3:
                        reason =  item[f'{default_prompt}_othercot'] + ". Therefore, the answer is "
                # elif args.model_name in ['DeepSeekR1-Qwen-1_5B','DeepSeekR1-Qwen-7B', 'DeepSeekR1-Qwen-14B', 'DeepSeekR1-Qwen-32B']:
                #     reason = "<think>\n" + item[f'{default_prompt}_thinking_CoT'] + "</think>"
                else:
                    reason = extract_reason(item[f'{default_prompt}_output'])
            else:
                # shuffle the subjects in the reasoning steps generated by LLM
                raise NotImplemented
        elif interfere == 'outputreason':
            default_role = 'math teacher'
            default_prompt = prompt.split('.')[0] + f'.{default_role}'
            cot_list = item[f'{default_prompt}_output_CoT'].split('.')
            for cot_list_index in range(len(cot_list)):
                if 'boxed' in cot_list[cot_list_index]:
                    cot_list = cot_list[:cot_list_index]
                    break
            reason = '.'.join(cot_list)
            if args.interfere_mode not in [1, 2, 3, 4]:
                reason = extract_reason(item[f'{default_prompt}_output'])
            elif args.interfere_mode == 1:
                reason = "<think>\n" + reason + ". So, let me directly conclude the answer. The answer is "
            elif args.interfere_mode == 2:
                reason = "<think>\n" + reason + ".</think>\nTherefore, the answer is "
            elif args.interfere_mode == 3:
                reason =  reason + ". Therefore, the answer is "
            else:
                raise NotImplemented
        elif interfere == 'simplereason':
            default_role = 'math teacher'
            default_prompt = prompt.split('.')[0] + f'.{default_role}'
            number1, number2 = item['number1'], item['number2']
            if dataset in ['Addition']:
                # default_prompt = prompt.split('.')[0] + f'.{default_role}'
                # problem_statement = item[f'{default_prompt}_input']
                # match = re.search(r'\n(What is the sum of \d+ and \d+\?)', problem_statement)
                # if match:
                    # question = match.group(1)
                reason = f'I need to figure out what is the sum of {number1} and {number2}. First, I will align the two numbers by their place values to ensure accurate addition.\n\nNext, I will add the digits starting from the rightmost digit (the ones place) and move to the left.\n\nIf the sum of any two digits exceeds 9, I will carry over the extra value to the next higher place value.\n\nI will continue this process for each place value until all digits have been added.\n\nFinally, I will compile the results to obtain the final sum.\n'

            elif dataset in ['Product']:
                # problem_statement = item[f'{prompt}_input']
                # match = re.search(r'\n(What is the product of \d+ and \d+\?)', problem_statement)
                # if question:
                #     question = match.group(1)
                reason = f'I need to figure out what is the product of {number1} and {number2}. First, I will align the numbers based on place value, writing one number above the other.\n\nNext, I will multiply each digit of the bottom number by each digit of the top number, starting from the rightmost digit of the bottom number.\n\nI will write each resulting partial product in its correct place value, shifting one position to the left for each new row.\n\nIf the product of any two digits is greater than 9, I will carry over the extra value to the next place value.\n\nI will continue this process until all digits have been multiplied.\n\nFinally, I will add all the partial products together to obtain the final product.'
                # else:
                #    raise ValueError("Problem statement does not contain a valid question.")
            
            if args.model_name in ['deepseek-reasoner', 'deepseek-r1', 'Pro/deepseek-ai/DeepSeek-R1', 'DeepSeekR1-Qwen-1_5B','DeepSeekR1-Qwen-7B', 'DeepSeekR1-Qwen-14B', 'DeepSeekR1-Qwen-32B', 'QwQ-32B']:
                if args.interfere_mode not in [1, 2, 3, 4]:
                    reason = reason
                elif args.interfere_mode == 1:
                    reason = "<think>\n" + reason + ". So, let me directly conclude the answer. The answer is "
                elif args.interfere_mode == 2:
                    reason = "<think>\n" + reason + "</think>\nTherefore, the answer is "
                elif args.interfere_mode == 3:
                    reason =  reason + ". Therefore, the answer is "
                elif args.interfere_mode == 4:
                    reason = "<think>" + reason + "</think>" + item[f'{default_prompt}_thinking_CoT'] + ".Therefore, the answer is"
            else:
                raise NotImplemented
        else:
            raise NotImplemented

    message = format_prompt(full_prompt, item)
    dataset = dataset.split(':')[0]
    if dataset in ['Addition', 'Product', 'GSM8K']:
        if args.interfere_mode in [1, 2, 3, 4]:
            message = f'{message}\n{reason}\nAnswer:'
        else:
            message = f'{message}\n{reason}\n'
    else:
        message = f'{message}\n{reason}\nThe correct option is:'

    # Handle list messages for interfere_mode 1 and 2
    if args.model_name in ['deepseek-reasoner', 'deepseek-r1', 'Pro/deepseek-ai/DeepSeek-R1', 'DeepSeekR1-Qwen-1_5B','DeepSeekR1-Qwen-7B', 'DeepSeekR1-Qwen-14B', 'DeepSeekR1-Qwen-32B', 'QwQ-32B']:
        default_role = 'math teacher'
        default_prompt = prompt.split('.')[0] + f'.{default_role}'
        distilled_instruction = item[f'{default_prompt}_input']
        # print(f'\n\n======================================\n\n default_prompt: {default_prompt}\n\n======================================')
        # print(f'\n\n======================================\n\n distilled_instruction: {distilled_instruction}\n\n======================================')
        
        # Replace role in the instruction
        if args.do_role == 'randomrole':
            distilled_instruction = distilled_instruction.replace('math teacher', item['role'])
        
        
        # Add bias sentence to the instruction
        is_math = dataset in ['Addition', 'Product', 'GSM8K']
        if args.do_bias == 'strongbias':
            bias_sentence = 'I think the correct answer is: {{biasanswer}}' \
                            if is_math else 'I think the correct option is: {{biasoption}}'
            distilled_instruction = add_bias_sentence(distilled_instruction, bias_sentence)
        elif args.do_bias == 'weakbias':
            bias_sentence = 'I think the correct answer is: {{biasanswer}}, but I’m curious to hear what you think.' \
                            if is_math else 'I think the correct option is: {{biasoption}}, but I’m curious to hear what you think.'
            distilled_instruction = add_bias_sentence(distilled_instruction, bias_sentence)
        elif args.do_bias == 'nobias':
            pass
        formatted_instruction = format_prompt(distilled_instruction, item)
        # if args.interfere_mode == 1:
        return [formatted_instruction, reason]
        # else:  # mode 2
        #     return [item[f'{default_prompt}_input'], reason]

    return message


def load_output(args):
    default_role = 'math teacher'
    output_file = f'{args.outdir}/output.{args.dataset}.{args.prompt}.{default_role}.{args.model_name}.json'
    if args.interfere_mode in [1, 2, 3, 4]:
        output_file = f'{args.outdir}/output.{args.dataset}.{args.prompt}.{default_role}.{args.model_name}.thinking.json'
        if args.do_reason == 'goldreason-r1':
            output_file = f'{args.outdir}/output.{args.dataset}.{args.prompt}.{default_role}.{args.model_name}.thinking.replace_golden.json'
    # if not os.path.exists(output_file):
    #     output_file = f'{args.outdir}/output.{args.dataset}.{args.prompt}.{default_role}.{args.model_name}.json'
    output_file = output_file.replace(' ', '_').replace(':', '_')
    with open(output_file, 'r') as fin:
        output = json.load(fin)
        if getattr(args, 'do_role', None) is not None:
            output = add_role(output, args.do_role)
        else:
            output = add_role(output, args.role)
        if getattr(args, 'do_bias', 'nobias') != 'nobias':
            # bias to wrong answer for default/gold reason, bais to right answer for random reason
            output = add_bias(args.dataset, output, wrong='random' not in args.do_reason)
        print(f'Loaded {len(output)} items from {output_file}')
    return output


def add_role(data, do_role):
    # make bias data
    for item in data:
        if do_role == 'defaultrole':
            item['role'] = 'math teacher'
        elif do_role == 'randomrole':
            role = random.choice(['detective', 'chef', 'judge'])
            item['role'] = role
        else:
            item['role'] = do_role
    return data


# add bias option for logical problems
def add_bias_option(data, wrong=True):
    # make bias data
    for item in data:
        if wrong:
            all_choices = [str(chr(65 + choice)) for choice in range(len(item['options']))]
            all_choices.remove(item['answer'])
            item['biasoption'] = random.choice(all_choices)
        else:
            item['biasoption'] = item['answer']
    return data


# add bias answer for math problems
def add_bias_answer(data, wrong=True):
    # make bias data
    for item in data:
        if wrong:
            # randomly change a digit in the number
            answer = item['answer']
            idx = random.randint(0, len(answer) - 1)
            digit = int(answer[idx])
            all_choices = [i for i in range(0, 10)]
            all_choices.remove(digit)
            new_digit = random.choice(all_choices)
            new_answer = answer[:idx] + str(new_digit) + answer[idx+1:]
            item['biasanswer'] = new_answer
        else:
            item['biasanswer'] = item['answer']
    return data


def add_bias(dataset, data, wrong=True):
    dataset = dataset.split(':')[0]
    if dataset in ['Addition', 'Product', 'GSM8K']:
        data = add_bias_answer(data, wrong=wrong)
    else:
        data = add_bias_option(data, wrong=wrong)
    return data


def get_prompt_name(args):
    treatment = args.do_reason
    if args.do_role != 'defaultrole':
        treatment = f'{treatment}_{args.do_role}'
    if args.do_bias != 'nobias':
        treatment = f'{treatment}_{args.do_bias}'
    return f'{args.prompt}.{treatment}'

def add_random_reason(args,data):
    if args.do_role == 'defaultrole':
        default_role = 'math teacher'
    else:
        raise NotImplemented
    random_reason_path = f'exp_cot/random_reason/random_reason.{args.dataset}.{args.prompt}.{default_role}.{args.model_name}.json'.replace(' ','_')
    with open(random_reason_path, 'r', encoding='utf-8') as f:
        random_reason_data = json.load(f)
    for d in data:
        d_id = d['id']
        random_reason_item = next((r for r in random_reason_data if r.get('id') == d_id), None)
        if random_reason_item:
            if args.interfere_mode == 1:
                d['random_reason'] = random_reason_item.get('random_reason_thinking_CoT', '')
            # elif args.interfere_mode == 2:
            #     d['random_reason'] = random_reason_item.get('random_reason_thinking', '')
            elif args.interfere_mode == 2:##still use thinking_CoT,but a close <thinking>
                d['random_reason'] = random_reason_item.get('random_reason_thinking_CoT', '')
            elif args.interfere_mode == 3:
                d['random_reason'] = random_reason_item.get('random_reason_thinking_CoT', '')
            elif args.interfere_mode == 4:
                d['random_reason'] = random_reason_item.get('random_reason_thinking_CoT', '')
            else:
                d['random_reason'] = random_reason_item.get('random_reason', '')
    return data




def intervene(args):
    sys.set_int_max_str_digits(10000)
    openai_api = OpenAIModel(args.api_base, args.api_key, args.model_name, args.stop_words, args.max_new_tokens)
    full_prompt = load_prompt(args.dataset, args.prompt, args.do_role, args.do_bias)
    prompt = get_prompt_name(args)

    random.seed(args.seed)
    np.random.seed(args.seed)
    data = load_output(args)

    # For randomreasonstart, randomreasonmiddle, randomreasonend
    if args.dataset in ['ProofWriter','FOLIO','LOGIQA'] and args.do_reason == 'randomreason':
        data = add_random_reason(args,data)
    # check file existencce
    # output_file = f'{args.outdir}/output.{args.dataset}.{prompt}.{args.model_name}.json'
    output_file = f'{args.outdir}/output.{args.dataset}.{prompt}.{args.model_name}.mode{args.interfere_mode}.json'
    output_file = output_file.replace(' ', '_').replace(':', '_')
    if os.path.exists(output_file):
        print(f'Exist file {output_file}')
        return None

    outputs = []
    accs = []
    dataset_chunks = [data[i:i + args.batch_size] for i in range(0, len(data), args.batch_size)]
    cnt_total = 0
    for chunk in tqdm(dataset_chunks):
        messages = [format_interfere_prompt(args, prompt, full_prompt, item, data) for item in chunk]
        cnt_exp = 0
        print('messages: ', messages)
        while True:
            if(cnt_exp > 3):
                batch_outputs = ['']
                break
            try:
                if len(messages) >= 2:
                    batch_outputs = openai_api.batch_generate(messages)
                else:
                    batch_outputs = [openai_api.generate(message, interfere_mode=args.interfere_mode) for message in messages]
                    # print("batch_outputs: ", batch_outputs)
                if(args.model_name in ['deepseek-reasoner', 'deepseek-r1', 'Pro/deepseek-ai/DeepSeek-R1']):
                    if args.interfere_mode > 0:
                        preds = [extract_answer(output[0], sample, args.dataset, args.interfere_mode) for sample, output in zip(chunk, batch_outputs)]
                    else:
                        preds = [extract_answer(output[0], sample, args.dataset) for sample, output in zip(chunk, batch_outputs)]
                elif(args.model_name in ['DeepSeekR1-Qwen-1_5B','DeepSeekR1-Qwen-7B', 'DeepSeekR1-Qwen-14B', 'DeepSeekR1-Qwen-32B', 'QwQ-32B']):
                    if args.interfere_mode == 1:
                        preds = [extract_answer(output[1], sample, args.dataset, args.interfere_mode) for sample, output in zip(chunk, batch_outputs)]
                    elif args.interfere_mode == 2 or args.interfere_mode == 4:
                        preds = [extract_answer(output[0], sample, args.dataset, args.interfere_mode) for sample, output in zip(chunk, batch_outputs)]
                    else:
                        preds = [extract_answer(output[0], sample, args.dataset) for sample, output in zip(chunk, batch_outputs)]
                else:
                    preds = [extract_answer(output, sample, args.dataset) for sample, output in zip(chunk, batch_outputs)]
                # preds = [extract_answer(output, sample, args.dataset) for sample, output in zip(chunk, batch_outputs)]
                # print('batch_out:', batch_outputs)
                print("success id: ", cnt_total)
                cnt_total += 1
                break
            except Exception as ex:
                print(ex)
                print('Sleep 10 seconds before retry ...')
                time.sleep(10)
                cnt_exp += 1
        for sample, output, message in zip(chunk, batch_outputs, messages):
            answer = sample[f'answer']
            if(args.model_name in ['deepseek-reasoner', 'deepseek-r1', 'Pro/deepseek-ai/DeepSeek-R1']):
                if args.interfere_mode > 0:
                    pred = extract_answer(output[0], sample, args.dataset, args.interfere_mode)
                else:
                    pred = extract_answer(output[0], sample, args.dataset)
            elif args.model_name in ['DeepSeekR1-Qwen-1_5B','DeepSeekR1-Qwen-7B', 'DeepSeekR1-Qwen-14B', 'DeepSeekR1-Qwen-32B', 'QwQ-32B']:
                if args.interfere_mode == 1:
                    pred = extract_answer(output[1], sample, args.dataset, args.interfere_mode)
                else:
                    pred = extract_answer(output[0], sample, args.dataset, args.interfere_mode)
            else:
                pred = extract_answer(output, sample, args.dataset)
            record_item = sample.copy()
            if args.model_name in ['deepseek-reasoner', 'deepseek-r1', 'Pro/deepseek-ai/DeepSeek-R1']:
                if args.interfere_mode in [1, 2, 3]:
                    record_item[f'{prompt}_input_user'] = message[0]
                    record_item[f'{prompt}_input_assistant'] = message[1]
                    record_item[f'{prompt}_output'] = output[0]
                else:
                    record_item[f'{prompt}_input'] = message
                    record_item[f'{prompt}_output'] = output
            elif args.model_name in ['DeepSeekR1-Qwen-1_5B','DeepSeekR1-Qwen-7B', 'DeepSeekR1-Qwen-14B', 'DeepSeekR1-Qwen-32B','QwQ-32B']:
                if args.interfere_mode == 1:
                    record_item[f'{prompt}_input_user'] = message[0]
                    record_item[f'{prompt}_input_assistant'] = message[1]
                    record_item[f'{prompt}_output'] = output[1] # Thinking CoT
                elif args.interfere_mode == 2 or args.interfere_mode == 3:
                    record_item[f'{prompt}_input_user'] = message[0]
                    record_item[f'{prompt}_input_assistant'] = message[1]
                    record_item[f'{prompt}_output'] = output[0]
                else:
                    record_item[f'{prompt}_input'] = message
                    record_item[f'{prompt}_output'] = output
            else:
                record_item[f'{prompt}_input_new'] = message
                record_item[f'{prompt}_output_new'] = output
            record_item[f'{prompt}_answer'] = pred
            record_item[f'{prompt}_result'] = (pred == answer)
            accs.append(pred == answer)
            outputs.append(record_item)

    print(f'acc_{prompt}:', np.mean(accs), f'({np.sum(accs)}/{len(accs)})')

    # output_file = f'{args.outdir}/output.{args.dataset}.{prompt}.{args.model_name}.json'
    # if args.interfere_mode > 0:
    interfere_mode = None
    if(args.interfere_mode == 0):
        interfere_mode = 'default'
    elif(args.interfere_mode == 1):
        interfere_mode = 'Y1'
    elif(args.interfere_mode == 2):
        interfere_mode = 'Y1-Z'
    elif(args.interfere_mode == 3):
        interfere_mode = 'Y'
    elif(args.interfere_mode == 4):
        interfere_mode = 'full'
    output_file = f'{args.outdir}/output.{args.dataset}.{prompt}.{args.model_name}.mode{interfere_mode}.json'
    output_file = output_file.replace(' ', '_').replace(':', '_')
    with open(output_file, 'w', encoding='utf-8') as fout:
        json.dump(outputs, fout, indent=2, ensure_ascii=False)
        print(f'Write {len(outputs)} items into {output_file}')


if __name__ == '__main__':
    ''' Call OpenAPI to answer nsamples questions from dataset using the prompt.
    '''
    parser = argparse.ArgumentParser()
    parser.add_argument('--outdir', type=str, default='./exp_cot/output')
    parser.add_argument('--api_base_num', type=int, default=0, choices=[0, 1, 2, 3], help='0: https://api.deepseek.com/beta, 1: http://localhost:8080/v1 2: http://localhost:8081/v1, 3:https://dashscope.aliyuncs.com/compatible-mode/v1' )
    parser.add_argument('--api_key', type=str, required=True)
    parser.add_argument('--model_name', type=str, default='gpt-3.5-turbo')  # gpt-3.5-turbo, text-davinci-003
    parser.add_argument('--stop_words', type=str, default='####')
    parser.add_argument('--max_new_tokens', type=int, default=8192)
    parser.add_argument('--dataset', type=str, default='GSM8K')
    parser.add_argument('--prompt', type=str, default='cot0shot')
    parser.add_argument('--batch_size', type=int, default=1)
    # do operator to intervene the random variables
    #   defaultrole: math teacher, randomrole: detective, chef, judge
    parser.add_argument('--do_role', type=str, default='defaultrole', choices=['defaultrole', 'randomrole'])
    #   nobias: no bias prompt, weakbias: weak bias prompt, strongbias: strong bias prompt
    parser.add_argument('--do_bias', type=str, default='nobias', choices=['nobias', 'weakbias', 'strongbias'])
    #   defaultreason: CoT from LLM generation, goldreason: golden CoT, randomreason: CoT with number, subject, negative interventions
    parser.add_argument('--do_reason', type=str, default='defaultreason', choices=['defaultreason', 'goldreason', 'randomreason', 'otherreason', 'goldreason-r1', 'outputreason', 'simplereason', 'outputreason'])
    #   interfere_mode: 0=default, 1=test Y1 internal causality, 2=test Y1 and Z(Y2) causality
    parser.add_argument('--interfere_mode', type=int, default=0, choices=[0, 1, 2, 3, 4])
    parser.add_argument('--seed', type=int, default=1)
    parser.add_argument('--api_base', type=str, default='https://api.deepseek.com/beta')
    args = parser.parse_args()

    # Set API base URL based on api_base_num
    if args.api_base_num == 0:
        args.api_base = 'https://api.deepseek.com/beta'
    elif args.api_base_num == 1:
        args.api_base = 'http://localhost:8080/v1'
    elif args.api_base_num == 2:
        args.api_base = 'http://localhost:8081/v1'
        args.max_new_tokens = 16384
    if args.api_base_num == 3:  
        args.api_base = 'https://dashscope.aliyuncs.com/compatible-mode/v1'  

    # print("base_num: ", args.api_base_num)
    # print("base: ", args.api_base)    

    random.seed(args.seed)
    np.random.seed(args.seed)
    
    print(args.interfere_mode)

    if (args.do_reason == 'goldreason' or args.do_reason == 'goldreason-r1') and args.dataset in ['FOLIO', 'LOGIQA']:
        print(f'{args.dataset} dataset does not support goldreason because it is not provided.')
    elif args.api_base_num not in [0, 1, 2, 3]:
        print(f'please choose a correct api_base.')
    else:
        intervene(args)

